database:
  connection_string: postgresql://<your connection string>
auth:
  jwt:
    secret_key: xyz
    expiration_time: 1000
    issuer: issuerstring
    audience: audiencestring
    subject: 'user'

  sign_in_url: cognito sign in url
