cms:
  database:
    connection_string: postgresql://<your connection string>
  auth:
    jwt:
      secret_key: xyz
      expiration_time: 1000
      issuer: issuerstring
      audience: audiencestring
      subject: 'user'
    kratos:
      host: kratos # kratos's name on the docker compose intranet network
      port: 4433
    sign_in_url: http://127.0.0.1:4455/welcome # Kratos login url
another_app:
  database:
    [...]
  auth:
    [...]
and_another_app:
  database:
    [...]
  auth:
    [...]
