# docker compose to stand up this project's Dockerfile along with a PostgreSQL instance
services:
  web:
    depends_on:
      - db
    build: .
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - CLIENT_ID=${CLIENT_ID}
      - POOL_ID=${POOL_ID}
      - REGION=${REGION}
    command: ./app --host=0.0.0.0 --port=8000
    networks:
      - intranet
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - intranet
networks:
  intranet: