// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"encoding/json"
	"time"
)

type File struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	Blob      []byte    `json:"blob"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	OwnerID   int32     `json:"owner_id"`
}

type User struct {
	ID         int32           `json:"id"`
	Name       string          `json:"name"`
	Email      string          `json:"email"`
	Attributes json.RawMessage `json:"attributes"`
	Password   string          `json:"password"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}
