// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type File struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Blob      []byte    `json:"blob"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	OwnerID   int32     `json:"owner_id"`
}

type Invoice struct {
	ID             int64     `json:"id"`
	Amount         float64   `json:"amount"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	UserID         int32     `json:"user_id"`
	OrgnaizationID int32     `json:"orgnaization_id"`
}

type Message struct {
	ID        int64     `json:"id"`
	ToID      int32     `json:"to_id"`
	Message   string    `json:"message"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	FromID    int32     `json:"from_id"`
}

type Organization struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID             int64           `json:"id"`
	OrganizationID sql.NullInt32   `json:"organization_id"`
	Name           string          `json:"name"`
	Email          string          `json:"email"`
	Attributes     json.RawMessage `json:"attributes"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}
